name: Monetag 24/7 Bot
on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Puppeteer
        run: npm install puppeteer-core
      - name: Run Bot
        run: node cpa_bot.js
