name: SproutGigs-Automation-24-7

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install puppeteer

      - name: Execution
        env:
          SPROUT_EMAIL: ${{ secrets.SPROUT_EMAIL }}
          SPROUT_PASS: ${{ secrets.SPROUT_PASS }}
        run: node super_bot.js
